[book]
authors = ["Ross Smyth"]
language = "en"
multilingual = false
src = "src"
title = "blog"

[output.html]
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]

[preprocessor.pagetoc]
